env:
  global:
    - CC_TEST_REPORTER_ID=12e701aaec0f7d955f351cba329594aa37b09a164b11c9858eace9b7c4bc9b13
language: php
php :
  - 5.6
  - 7.0

env:
  - CC_TEST_REPORTER_ID=12e701aaec0f7d955f351cba329594aa37b09a164b11c9858eace9b7c4bc9b13

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)